edition = "2024"

max_width = 120
format_code_in_doc_comments = true
# from bevy
use_field_init_shorthand = true
newline_style = "Unix"

# requires nightly
unstable_features = true
trailing_comma = "Vertical"
# from bevy
imports_granularity = "Crate"
wrap_comments = true
comment_width = 100

